name: Deploy to GitHub Pages

on:
  push:
    branches:
      - bun

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Install Dependencies
        run: bun install

      - name: Build Project
        run: bun run build

      - name: Export Project
        run: bun export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # the output directory of your build
